# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: jplaw2epub

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/jplaw2epub
    binary: jplaw2epub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: ngs
    name: jplaw2epub
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  disable: false

brews:
  - repository:
      owner: ngs
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/ngs/jplaw2epub
    description: "Convert Japanese Standard Law XML Schema into EPUB files"
    license: MIT
    test: |
      system "#{bin}/jplaw2epub -h"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/ngs/jplaw2epub
    description: "Convert Japanese Standard Law XML Schema into EPUB files"
    maintainer: Atsushi Nagase <a@ngs.io>
    license: MIT
    vendor: ngs.io
    formats:
      - deb
      - rpm
      - apk
